### ISSUE TITLE
rewrite connectors samples to use pekko libs

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-pekko-connectors#57]
* most pekko projects have snapshot jars available (on repository.apache.org)
* we can skip any samples that can't yet be migrated due to libs not being available
* https://github.com/apache/incubator-pekko-connectors-samples
* we have docs in this project that refer to these samples - so the docs need to point at the updated samples or be temporarily removed

**Comment by reypader** [comment]
@pjfanning , are there legal headers that need to be added for these?

also, I'm trying to work on this.

I'm having troubles with `scala.compat.java8.FutureConverters._`.

`org.apache.pekko.util.FutureConverters._`  seems inaccessible?

**Comment by pjfanning** [comment]
@reypader do not use `scala.jdk.FutureConverters._` - that will not work with older scala versions like 2.12.x.

Use the Pekko FutureConverters. Upgrade the Pekko jar to be 1.0.0. The snapshot jar that is in use right now may not have `org.apache.pekko.util.FutureConverters` buthe Pekko 1.0.0 has it.

**Comment by reypader** [comment]
I did try to use `org.apache.pekko.util.FutureConverters` but I'm getting errors with access

```
...
[error] /Users/rey.pader/GitProjects/incubator-pekko-connectors-samples/alpakka-sample-file-to-elasticsearch/src/main/scala/samples/javadsl/RunOps.scala:9:30: object FutureConverters in package util cannot be accessed as a member of package org.apache.pekko.util from package javadsl in package samples
[error] import org.apache.pekko.util.FutureConverters._
[error]                              ^
[error] /Users/rey.pader/GitProjects/incubator-pekko-connectors-samples/alpakka-sample-file-to-elasticsearch/src/main/scala/samples/javadsl/RunOps.scala:19:37: value asJava is not a member of scala.concurrent.Future[Seq[java.nio.file.Path]]
[error]     scaladsl.RunOps.listFiles(path).asJava
...
```

I'm positive I'm using Pekko 1.0.0.

```
...
[info]   +-org.apache.pekko:pekko-actor_2.13:1.0.0 [S]
[info]   | +-com.typesafe:config:1.4.2
[info]   | 
[info]   +-org.apache.pekko:pekko-connectors-elasticsearch_2.13:0.0.0+129-1853d802-SN..
[info]   | +-com.fasterxml.jackson.core:jackson-core:2.14.3
[info]   | +-com.fasterxml.jackson.core:jackson-databind:2.14.3
[info]   | | +-com.fasterxml.jackson.core:jackson-annotations:2.14.3
[info]   | | +-com.fasterxml.jackson.core:jackson-core:2.14.3
...
```

**Comment by pjfanning** [comment]
So FutureConverters is package private.

So use scala.jdk class (as you were intending to use) if the sample is set up to run with Scala 2.13.

**Comment by sfali** [comment]
Is there any specific connector(s) that need to be imported?
